name: build

on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  maven:
    name: Project build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven build
        run: ./mvnw --batch-mode --no-transfer-progress -DskipTests=false verify
